name: Workflow Status

on:
  workflow_run:
    workflows: ["CI Tests", "Build and Test", "Code Quality", "Security Scan"]
    types: [completed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    
    steps:
    - name: Check workflow status
      run: |
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Status: ${{ github.event.workflow_run.conclusion }}"
        echo "URL: ${{ github.event.workflow_run.html_url }}"
        
        if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
          echo "✅ Workflow passed"
        elif [ "${{ github.event.workflow_run.conclusion }}" = "failure" ]; then
          echo "❌ Workflow failed"
        else
          echo "⚠️ Workflow status: ${{ github.event.workflow_run.conclusion }}"
        fi
